[tool.uv.workspace]
members = [
    "jfm",
]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q"
testpaths = [
    "jfm/tests",
]

# Ruff can live here for the workspace; per-package overrides may exist.
[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "B",  # bugbear
]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

