name: Bug report
description: Report a problem to help us improve
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior.
      placeholder: When I did X, I expected Y but saw Z…
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Minimal steps to reproduce.
      placeholder: 1) … 2) … 3) …
  - type: input
    id: version
    attributes:
      label: Version/commit
      description: Version tag or commit SHA.
  - type: textarea
    id: extra
    attributes:
      label: Additional context

