name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this useful? Who benefits?
  - type: textarea
    id: approach
    attributes:
      label: Proposed approach
      description: Optional. Sketch any implementation ideas or trade-offs.

